name: dart_vlc
description: A media playback library for Dart & Flutter. Based on libVLC & libVLC++.
version: 0.0.4
homepage: https://github.com/NazarKostetskiy/dart_vlc
repository: https://github.com/NazarKostetskiy/dart_vlc
documentation: https://github.com/alexmercerind/dart_vlc/blob/master/README.md

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.28
  path: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: DartVlcPlugin
      linux:
        pluginClass: DartVlcPlugin
